### ISSUE TITLE
Visiting docs.vapor.codes redirects to version 3 documentation

### ISSUE THREAD

**Issue by mattt** [vapor/docs#489] opened 2020-05-19 18:34 UTC
When I visit https://docs.vapor.codes/, I'm redirected to https://docs.vapor.codes/3.0/. 

Since version 4 is now available, this should redirect to the latest documentation instead: https://docs.vapor.codes/4.0/

**Comment by ThonyF** [comment] 2020-05-20 20:26
Yes, it is, because all Vapor 4 documentation isn't ready yet, like the parts of Fluent and Leaf.
It's like when you create a new project, you must still use the command `vapor-beta` and not `vapor`

**Comment by mattt** [comment] 2020-05-20 20:40
I guess I'm confused about Vapor's versioning strategy, then. Vapor is currently at version 4.5.1, but major components like Fluent and Leaf are still 4.0 release candidates. If the idea is for Vapor to be an all-in-one, batteries-included framework like Rails, it's important for releases to be coordinated.

**Comment by ThonyF** [comment] 2020-05-20 21:29
I thing so too but, Rome was not built in a day.
Ruby has 25 years old while Swift has 6 years old and Ruby on Rails has 16 years old while Vapor has 4 years old so, there is a long way to go before to be like Rails.

**Comment by mattt** [comment] 2020-05-20 21:46
@ThonyF Yes, big things take time to build, but that's all the more reason to practice release coordination and documentation. There's nothing stopping a project from doing this from Day 1.

**Comment by tanner0101** [comment] 2020-05-28 17:02
Dupe of https://github.com/vapor/website/issues/64. We're waiting until Fluent is released to switch things over.

**Closed by tanner0101** 2020-05-28 17:02 UTC
